name: swetrix_flutter
description: A lightweight Swetrix Events API client for Flutter and Dart apps.
version: 0.1.2
homepage: https://swetrix.com
repository: https://github.com/ehwplus/swetrix_flutter
issue_tracker: https://github.com/ehwplus/swetrix_flutter/issues

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ">=1.1.0 <2.0.0"
  meta: ">=1.12.0 <2.0.0"
  package_info_plus: ">=8.0.0 <10.0.0"
  device_info_plus: ">=11.0.0 <13.0.0"
  shared_preferences: ">=2.0.6 <3.0.0"
  uuid: ">=4.5.0 <5.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=5.0.0 <7.0.0"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # This package does not bundle assets or fonts by default.
